version: '3.8'
services:
  frontend:
    build: ./client
    expose:
      - "80"
    environment:
      - VITE_API_URL=https://olehkyryliuk.com
    restart: always

  backend:
    build: ./server
    expose:
      - "8080"
    restart: always

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
